language: node_js
node_js:
- node
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: LnGkKQbS231sXG0U8fY+uKngo3w9hNujKow23nVA1qe9wAAgE72asHyDRn68bidRZfAHgdvLMiraFgLTSEq5ZQXrs7KUVNYFi2DwmgPYdASGfS/sgYAOapTck6HrJVSnQoUghfBITTOc74X2tUfQ1eC9QjYVjq5LFwJDEspfljHlaFH1p1xpIW2GBWJ4vvhY2uDoAwJbO0x3yBSufS4vX7Pl+6FfdXG2RzedjId90M34rlx20E5IC2KhbdFSXo+pUYT31i/awTVz4Jz1/GrUa6drR0/q4Ud94OV8Z2XygBfVRX4E7mmGGnUvNpk6P8RbssWwiZp8a4Tl+QD5mtfMuq53goXWu23o1sNnSSBT+btvwnN5nVYO9RxTW1eg3aitjsy4K13SME90ITZrysdkVR5oiyyI6OrgQOSJjuatJsZs/S6btRvHYFONsJX2OYG+Rbi9UOGgmuBGTMzGLLmZ6r+VMD5yrTAtOfvY2/5EOawACDBJheEJpcp52eiuUpTq1jG4rXbpFK3FinRGxog/rRKxaXT9QZTO4Hq5cyWyzvlCUVaVi453p18SecdHmU+N1G23lvWPlzneNlBl3sUJsB15kqQAIhOdr4Wsz1Aq6TBF4QuunJfixZlJMly1k5eQFLysMJUB5DMgLOTFlt7ha7h0TZnHBYUuxdxtDkf9H6M=
  app: cheer-io
  on:
    repo: cheer-app/cheer
